//! `example_table` — delete this migration (and its entity in
//! `{{project-name}}-db`, once you add one) after your first real migration
//! exists; it's here so `cargo run -p {{project-name}}-migration -- up`
//! does something real out of the box.

use sea_orm_migration::{prelude::*, schema::*};

#[derive(DeriveIden)]
pub enum ExampleTable {
    Table,
    Id,
    Name,
    CreatedAt,
}

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ExampleTable::Table)
                    .if_not_exists()
                    // UUID v7, generated by the application: time-sortable, so
                    // it indexes well as a primary key without a DB extension.
                    .col(pk_uuid(ExampleTable::Id))
                    .col(string(ExampleTable::Name))
                    .col(
                        timestamp_with_time_zone(ExampleTable::CreatedAt)
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.drop_table(Table::drop().table(ExampleTable::Table).to_owned()).await
    }
}
